Document: kcmsystemd
Title: Debian kcmsystemd Manual
Author: <insert document author here>
Abstract: This manual describes what kcmsystemd is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/kcmsystemd/kcmsystemd.sgml.gz

Format: postscript
Files: /usr/share/doc/kcmsystemd/kcmsystemd.ps.gz

Format: text
Files: /usr/share/doc/kcmsystemd/kcmsystemd.text.gz

Format: HTML
Index: /usr/share/doc/kcmsystemd/html/index.html
Files: /usr/share/doc/kcmsystemd/html/*.html
